### ISSUE TITLE
Styl kodowania

### ISSUE THREAD

**Issue by Arusekk** [Antek55/clicka#4]
Jest stronka, która się integruje z GitHubem, a nazywa się Codacy. Bardzo fajnie by ją wziąć sobie do serducha. Przy okazji jest też inna stronka, co się nazywa [Travis CI](https://travis-ci.org) w plecy, a także trzecia: coveralls (jest też inna, z której korzysta sam [python](https://github.com/python/cpython), ale nie pomnę nazwy). Będzie fajnie, bo będzie samo sprawdzać, czy pull requesty są ładne, czy nie, i gdzie coś się teoretycznie może wysypać.

**Comment by Antek55** [comment]
# zacnie
ale trzeba wybierać czy można wszystkie naraz? I czy ma sens wszystkie czy się pokrywają

**Comment by Arusekk** [comment]
Są to z grubsza trzy różne bajki:
 * Najbardziej przyda się ten [Travis](https://travis-ci.org). Sprawdza, czy projekt się buduje, i ewentualnie, czy testy działają (jeśli są).
 * Ten od pythona zwie się [Codecov](https://codecov.io), a pokrywa swą funkcjonalność z [Coveralls](https://coveralls.io). Sprawdzają one stopień pokrycia kodu przez testy (najpierw trzeba by jakieś dać xD). Wolałbym to pierwsze, bo nie ma czerwonej gwiazdy.
 * [Codacy](https://www.codacy.com) sprawdza, czy kod jest "seksowny". Przyda się, żeby dało się pracować z kodem, wykrywa podobne kwiatki, co poprawiłem w #5.

**Comment by Antek55** [comment]
testów nie ma i nie bardzo wiem jakie mogłyby być, każdy commit testuję ogólnie na localhoście a potem sam się testuje na produkcji (xd)

**Comment by Antek55** [comment]
### Codacy już jest

**Comment by Arusekk** [comment]
# Myślisz, żeby wrzucić też travisa?

wtedy można zacząć myśleć o testach

**Comment by Antek55** [comment]
# W istocie można by tak też uczynić
